Update tcst

diff --git a/tcst b/tcst
--- a/tcst
+++ b/tcst
@@ -1,20 +1,13 @@
 #!/bin/bash
 
-if ! find -type d -wholename "./src" > /dev/null
-then
-	echo \"src\" directory not found >&2
-	exit 1
-fi
-
-if [[ $# -lt 1 ]] || $([[ $# -eq 1 ]] && [[ $1 == "--help" ]] || [[ $1 == "-h" ]])
-then 
-	echo Usage: tcst \[-h \| --help\] CHECK_FILE_DIRECTORY
+printHelpMessage() {
+	echo Usage: tcst \[OPTIONS\]
 	echo C testing framework.
 	echo Compiles and runs C files whose names begin with \"test\"
 	echo then compares the output of these files with the expected
 	echo output found within the check files from the given
 	echo CHECK_FILE_DIRECTORY.
-echo
+	echo
 	echo Options:
 	echo "    -h, --help                       displays this message"
 	echo "    -o, --output                     outputs expected/actual output"
@@ -25,16 +18,35 @@ echo
 	echo "    CHECK_FILE_DIRECTORY             absolute path to the directory"
 	echo "                                     containing the check files for"
 	echo "                                     the tests"
-	echo
 	echo Exit status:
-	echo 
 	echo 0 if OK
 	echo 1 if \"src\" directory not found
-	echo 2 if not enough parameters
+	echo 2 if not enough parameters / wrong parameters
 	echo 3 if check files directory does not exist
 	echo 4 if check files directory is empty
 	echo 10 if some test failed
-echo 
+	echo 
+	echo Expected directory structure:
+	echo "./"
+	echo "|--src"
+	echo "| |--test*.c"
+	echo "| |--test*.c"
+	echo "| |--SUBDIRECTORY "
+	echo "| | |--test*.c"
+	echo "| | | ..."
+	echo "| | ..."
+	echo "| ..."
+}
+
+if ! find -type d -wholename "./src" > /dev/null
+then
+	echo \"src\" directory not found >&2
+	exit 1
+fi
+
+if [[ $# -lt 1 ]] || $([[ $# -eq 1 ]] && [[ $1 == "--help" ]] || [[ $1 == "-h" ]])
+then 
+	printHelpMessage
 	if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]
 	then
 		exit 0
@@ -46,12 +58,30 @@ outputOnFailed=0
 displayCompilerErrors=0
 totalNoOfTests=0
 noOfSuccessfullTests=0
+checkFileDirectory=0
 
 for param in $@
 do
 	if [[ $param != "-h" ]] && [[ $param != "--help" ]] && [[ $param != "-o" ]] && [[ $param != "--output" ]] && [[ $param != "-c" ]] && [[ $param != "--display-compiler-errors" ]]
 	then
-		checkFileDirectory=$param
+		if [[ $param == -* ]]
+		then
+			printHelpMessage
+			exit 2
+		fi
+		if [[ $checkFileDirectory == 0 ]]
+		then
+			checkFileDirectory=$param
+		else
+			printHelpMessage
+			exit 2
+		fi
+	fi
+
+	if [[ $param == "-h" ]] || [[ $param == "--help" ]]
+	then 
+		printHelpMessage
+		exit 0
 	fi
 
 	if [[ $param == "-o" ]] || [[ $param == "--output" ]]
